spring:
  profiles:
    include: private
  h2: # H2 Setting Info
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info (in-memory)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true